### PR TITLE
Refactoring, finalization and build system migration

### PR DESCRIPTION
**Pull request by paulianttila**
Thanks  for your contrib ! The migration  to new build system is Very useful !!! Can we write via mail ? Thanks  . Luca 

Ps tomorrow i'll try the new edits

### CODE REVIEW

**Comment by lucacalcaterra** [comment]
I compiled with Vs Code and seems to be ok. Great work !

Anyway there are some warnings that can be fixed. I'll provide to do it, in nearest feature we can pull to openhab for release the binding with master distro.

**Comment by paulianttila** [comment]
> in nearest feature we can pull to openhab for release the binding with master distro

That was my plan as well. The problem is that you repo is not a fork of the openhab2-addons repo, so you can't make PR from existing repo. You repo obviously is missing parent pom and karaf feature files which should updated by the PR as well.

**Comment by lucacalcaterra** [comment]
> > in nearest feature we can pull to openhab for release the binding with master distro
> 
> That was my plan as well. The problem is that you repo is not a fork of the openhab2-addons repo, so you can't make PR from existing repo. You repo obviously is missing parent pom and karaf feature files which should updated by the PR as well.

I know ... was in my plans, but i've not so much time.

Thanks for your contribution, i'm not a full time developer and don't know very well Java.

I release a jar , but probably need to wait if you count to post other edits...

**Comment by lucacalcaterra** [comment]
ps ... do you develop with vs code ?

**Pull request merged**
