### PR TITLE
Many improvements

### PR DESCRIPTION
**Pull request by paulianttila**

### CODE REVIEW

**Comment by paulianttila** [comment]
There is still race condition possibility in deviceStatus handling (MelCloudDeviceHandler). deviceStatus is periodically updated by scheduler and if command is send exactly in the same time, deviceStatus might be corrupted as cmdtoSend is just reference to same deviceStatus. 

I don't fully understand the MELCloud effectingFlag and hasPendingCommand concept, so for me it's rather difficult to fix this issue.

**Comment by paulianttila** [comment]
I modified deviceStatus sending to contain only needed fields (hopefully). Previously, binding send the whole deviceStatus including e.g. wether forecast information back to MELCloud.

**Comment by paulianttila** [comment]
Race condition possibility should be now fixed (not 100% happy about the solution).

**Comment by paulianttila** [comment]
@lucacalcaterra, ready to merge

**Comment by lucacalcaterra** [comment]
> @lucacalcaterra, ready to merge

I've no time to study the changes.

I trust your work and I merge. ok ?

**Comment by lucacalcaterra** [comment]
it's right to include in git repo  the .gitignore files and .vscode (for build the jar) ? or leave it like that
?

**Comment by lucacalcaterra** [comment]
or ... fork the official openhab2-addons repo and merge our binding (instead of it's alone ) ?

**Comment by paulianttila** [comment]
> it's right to include in git repo the .gitignore files and .vscode

openhab2-addons repo contains already .gitignore file (see https://github.com/openhab/openhab2-addons/blob/master/.gitignore). As you can see .vscode is also ignored there.

You should make full fork from openhab2-addons repo and merge melcloud binding there. Please, create e.g. melcloud branch and do not merge directly to the master branch. After that we can modify karaf feature files, etc before PR.

You should also sign the work accordingly (see https://www.openhab.org/docs/developer/contributing.html) and also add me by "Also-by: " tag.

**Comment by lucacalcaterra** [comment]
@paulianttila 
I created a repo forked from official oh2-addons and started a new branch named melcloud on it, copying the melcloud binding on the bundles dir (as it is , losting all commits history, a new, zero copy)

I invited you, let me know if it's ok and we can start to adjust for submit a PR

**Comment by paulianttila** [comment]
Thanks Luca, I might have couple of hours today, but if not I will continue during next week.

**Comment by lucacalcaterra** [comment]
I realized that the repo is probably not good. I ran the setup for VsCode
but the Openhab team considered experimental VsCode.
I'll probably have to recreate the branch.
I'll update you

Il giorno gio 27 giu 2019 alle ore 11:44 pali <notifications@github.com> ha
scritto:

**Comment by lucacalcaterra** [comment]
@paulianttila  Do you use vscode or eclipse for development ?

**Comment by paulianttila** [comment]
I use Eclipse

**Comment by lucacalcaterra** [comment]
I recreated repo and melcloud branch, invited you as collaborator.

Let me know if steps i've done are corrects.

Luca

Il giorno gio 27 giu 2019 alle ore 15:58 pali <notifications@github.com> ha
scritto:

**Pull request merged**
